### ISSUE TITLE
Importing meshes in other format than .mix

### ISSUE THREAD

**Issue by vbeliveau** [meshmixer/mm-api#13]
It would be great if other mesh format (.stl, .obj, etc) could be imported through the API. Right now only .mix files can open.

**Comment by 3DLIRIOUS** [comment]
You can import other formats. Here's a function that will do so:

```
def import_mesh(remote, file_in=None):
    """ Import a mesh file

    mesh_object: the object ID of the mesh object
    """

    mesh_object = mm.scene.append_objects_from_file(remote, file_in)
    print('object ID = %s' % mesh_object)
    return mesh_object
```

This and a few other helper functions can be found in [mmlirious.py](https://github.com/3DLIRIOUS/pylirious/blob/master/pylirious/mmlirious.py).

**Comment by vbeliveau** [comment]
Great, I'll try this out!

**Comment by vbeliveau** [comment]
Unfortunately this function does not appear to work properly. When running

```
from mmRemote import *;
import mm

remote = mmRemote();
remote.connect();
mesh_object = mm.scene.append_objects_from_file(remote,'bunny.stl')
remote.shutdown();
```

or even

```
import mmapi
from mmRemote import *;

remote = mmRemote();
remote.connect();
cmd = mmapi.StoredCommands()
key = cmd.AppendSceneCommand_AppendMeshFile('bunny.stl');
remote.runCommand(cmd)
remote.shutdown();
```
the function does return an empty list and the object is not loaded. No error or warning is either returned. Any idea what's going on? I tried different file format and the result was the same.

**Comment by rms80** [comment]
in your second code (directly using StoredCommands), you would need to send the key to GetSceneCommandResult_AppendMeshFile() to get the list of new objects, after you call runCommand. Not sure if you tried that.

Also are you certain that the file you are trying to load is in the path?

(this API call definitely works, although I am using it from C# and not Python...)

**Comment by vbeliveau** [comment]
Thanks for your suggestions Ryan. My bad I wasn't giving the path with the correct sep; I usually program under linux and was using `\` instead of `\\` .
